import { Controller, Get, Post, Body, Param, Delete, Res } from '@nestjs/common';
import type { Response } from 'express';
import { EstimationService } from './estimation.service';
import { CreateEstimateDto } from './dto/create-estimate.dto';
import { CreateEstimateSectionDto } from './dto/create-estimate-section.dto';
import { CreateEstimateItemDto } from './dto/create-estimate-item.dto';
import { CreateEstimateRateComponentDto } from './dto/create-estimate-rate-component.dto';
import { PdfService } from '../pdf/pdf.service';

@Controller('estimation')
export class EstimationController {
  constructor(
    private readonly estimationService: EstimationService,
    private readonly pdfService: PdfService,
  ) {}

  @Post()
  createEstimate(@Body() dto: CreateEstimateDto) {
    return this.estimationService.createEstimate(dto);
  }

  @Get('project/:projectId')
  getEstimatesByProject(@Param('projectId') projectId: string) {
    return this.estimationService.getEstimatesByProject(projectId);
  }

  @Get()
  getAllEstimates() {
    return this.estimationService.getAllEstimates();
  }

  @Get(':id')
  getEstimateById(@Param('id') id: string) {
    return this.estimationService.getEstimateById(id);
  }

  @Post('section')
  createSection(@Body() dto: CreateEstimateSectionDto) {
    return this.estimationService.createSection(dto);
  }

  @Post('item')
  createItem(@Body() dto: CreateEstimateItemDto) {
    return this.estimationService.createItem(dto);
  }

  @Post('component')
  createRateComponent(@Body() dto: CreateEstimateRateComponentDto) {
    return this.estimationService.createRateComponent(dto);
  }

  @Delete(':id')
  deleteEstimate(@Param('id') id: string) {
    return this.estimationService.deleteEstimate(id);
  }

  @Delete('section/:id')
  deleteSection(@Param('id') id: string) {
    return this.estimationService.deleteSection(id);
  }

  @Delete('item/:id')
  deleteItem(@Param('id') id: string) {
    return this.estimationService.deleteItem(id);
  }

  @Delete('component/:id')
  deleteRateComponent(@Param('id') id: string) {
    return this.estimationService.deleteRateComponent(id);
  }

  @Get(':id/pdf')
  async downloadEstimatePdf(@Param('id') id: string, @Res() res: Response) {
    const estimate = await this.estimationService.getEstimateById(id);
    if (!estimate) {
      return res.status(404).json({ message: 'Estimate not found' });
    }

    const buffer = await this.pdfService.generatePdf({
      title: `Project Estimate`,
      data: {
        estimate,
        sections: estimate.sections || [],
      },
      templateFn: this.estimatePdfTemplate,
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="estimate.pdf"');
    res.end(buffer);
  }

  private estimatePdfTemplate(doc: any, data: any) {
    const { estimate, sections } = data;

    doc.fontSize(20).text(estimate.title, { align: 'center' });
    doc.moveDown();

    doc.fontSize(12).text(`Project: ${estimate.project.name}`);
    doc.text(`Prepared by: ${estimate.creator.name}`);
    doc.text(`Date: ${new Date(estimate.createdAt).toDateString()}`);
    doc.moveDown(2);

    sections.forEach((section: any) => {
      doc.fontSize(14).text(section.name, { underline: true });
      doc.moveDown(0.5);

      section.items.forEach((item: any, index: number) => {
        doc.fontSize(12).text(
          `${index + 1}. ${item.description} — Qty: ${item.quantity} ${item.unit} @ ₹${item.rate} = ₹${item.amount}`,
        );

        // Rate analysis breakdown
        item.components.forEach((c: any) => {
          doc.fontSize(10).text(
            `   - ${c.type}: ${c.name} — ${c.quantity || ''} ${c.unit || ''} × ₹${c.rate} = ₹${c.cost}`,
          );
        });

        doc.moveDown(0.5);
      });

      doc.moveDown();
    });

    doc.fontSize(16).text(`Total Estimated Cost: ₹${estimate.totalCost}`, {
      align: 'right',
    });

    doc.moveDown(2);

    doc.fontSize(10).text('Generated by CivilDesk Estimation System', {
      align: 'center',
    });
  }
}